"use client"
import '../../Styles/global.css'
import '@fortawesome/fontawesome-svg-core/styles.css'; 
import type { Metadata } from 'next'
import Header from "../../Components/Header"
import Footer from '../../Components/Footer'
import Login from "../../Components/Login"
import Register from '../../Components/Register'
import {Roboto} from "next/font/google"
import { useState } from 'react';
const roboto = Roboto ({
  subsets : ['latin'],
  weight : ['400'],
  style :['normal']
})
export const metadata: Metadata = {
  title: 'trích xuất CMND',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [showModalLogin,setShowModalLogin]=useState(false)
  const [showModalRegister,setShowModalRegister]=useState(false)
  return (
    <html lang="en">
      <body className={`${showModalLogin || showModalRegister ? ('showForm'):('')} ${roboto.className}`} >
        {showModalLogin ? (<Login showModalLogin={showModalLogin} setShowModalLogin={setShowModalLogin}
        showModalRegister={showModalRegister} setShowModalRegister={setShowModalRegister}/>) :""}
        {showModalRegister ? (<Register showModalRegister={showModalRegister} setShowModalRegister={setShowModalRegister}
        showModalLogin={showModalLogin} setShowModalLogin={setShowModalLogin}/>):""}
        <div className='main'>
          <Header showModalLogin={showModalLogin} setShowModalLogin={setShowModalLogin}/>
          <main>
            {children} 
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
